'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("833302091790417920")> _
		Public Property appid() As String
			Get
				Return (DirectCast(Me("appid"), String))
			End Get
			Set(ByVal value As String)
				Me("appid") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property details() As String
			Get
				Return (DirectCast(Me("details"), String))
			End Get
			Set(ByVal value As String)
				Me("details") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("SG Cracked Minecraft Server")> _
		Public Property status() As String
			Get
				Return (DirectCast(Me("status"), String))
			End Get
			Set(ByVal value As String)
				Me("status") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("icon")> _
		Public Property lik() As String
			Get
				Return (DirectCast(Me("lik"), String))
			End Get
			Set(ByVal value As String)
				Me("lik") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("Ham5teak")> _
		Public Property lit() As String
			Get
				Return (DirectCast(Me("lit"), String))
			End Get
			Set(ByVal value As String)
				Me("lit") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property sik() As String
			Get
				Return (DirectCast(Me("sik"), String))
			End Get
			Set(ByVal value As String)
				Me("sik") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property sit() As String
			Get
				Return (DirectCast(Me("sit"), String))
			End Get
			Set(ByVal value As String)
				Me("sit") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("https://discord.gg/QNfQmHg")> _
		Public Property b1u() As String
			Get
				Return (DirectCast(Me("b1u"), String))
			End Get
			Set(ByVal value As String)
				Me("b1u") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("Join Discord")> _
		Public Property b1t() As String
			Get
				Return (DirectCast(Me("b1t"), String))
			End Get
			Set(ByVal value As String)
				Me("b1t") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("http://shop.ham5teak.xyz/")> _
		Public Property b2u() As String
			Get
				Return (DirectCast(Me("b2u"), String))
			End Get
			Set(ByVal value As String)
				Me("b2u") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("Visit Shop")> _
		Public Property b2t() As String
			Get
				Return (DirectCast(Me("b2t"), String))
			End Get
			Set(ByVal value As String)
				Me("b2t") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("True")> _
		Public Property yes() As Boolean
			Get
				Return (DirectCast(Me("yes"), Boolean))
			End Get
			Set(ByVal value As Boolean)
				Me("yes") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property no() As Boolean
			Get
				Return (DirectCast(Me("no"), Boolean))
			End Get
			Set(ByVal value As Boolean)
				Me("no") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("True")> _
		Public Property dark() As Boolean
			Get
				Return (DirectCast(Me("dark"), Boolean))
			End Get
			Set(ByVal value As Boolean)
				Me("dark") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property light() As Boolean
			Get
				Return (DirectCast(Me("light"), Boolean))
			End Get
			Set(ByVal value As Boolean)
				Me("light") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("True")> _
		Public Property Enabled() As Boolean
			Get
				Return (DirectCast(Me("Enabled"), Boolean))
			End Get
			Set(ByVal value As Boolean)
				Me("Enabled") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property Disabled() As Boolean
			Get
				Return (DirectCast(Me("Disabled"), Boolean))
			End Get
			Set(ByVal value As Boolean)
				Me("Disabled") = value
			End Set
		End Property
	End Class
End Namespace
